### ISSUE TITLE
Hamcrest domain ownership / contact info

### ISSUE THREAD

**Issue by offbyone** [hamcrest/hamcrest.github.com#12]
Hey, folks; PyHamcrest maintainer here.

Looking at hamcrest.org today, we are not getting SSL configured properly and that appears to stem from the A records for hamcrest.org being misconfigured. I see a bunch of issues in here regarding this, and no sense of who owns the domain name for hamcrest.org.

Can the person who has control over it please speak up? If administering it is a hassle, I'm also happy to take ownership of it and manage this, if you want.

**Comment by scarytom** [comment]
I think the owner is Drew Bourne

You should be able to reach him via email using:
drew AT firstbourne.com

**Comment by drewbourne** [comment]
Update: @offbyone and I are in contact. I'll transfer the domain over to Chris. 

In the meantime I've updated the A and CNAME records following the steps in [Managing a custom domain for your GitHub Pages site](https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site). 

Can an owner on this repo confirm that the Enforce HTTP option is enabled? See [Securing your GitHub Pages site with HTTPS](https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/securing-your-github-pages-site-with-https).

**Comment by sf105** [comment]
Thanks for this. Could we put it into an account where more than one person knows the details? Resilience and all that?

I also have hamcrest.io which will expire in a little while.

S

**Comment by drewbourne** [comment]
I'm happy to transfer the domain. Let me know who will coordinate and I'll provide the auth code via email.

**Comment by offbyone** [comment]
I don't mind taking it over; I plan to use Route53 domains for it. I'm not sure how a group of individuals would collaborate to share a domain otherwise, though. I'm open to ideas.

**Comment by sf105** [comment]
Previously I’ve used a special account with a registrar where several people know the login details.

S

**Comment by offbyone** [comment]
I'm leery of doing that because attaching payment instruments to it for autorenewal is a risk. I trust y'all reasonably well, but at the same time...

Also, eesh, it's another damn account :) 

I dunno. If someone else wants to take it as a single point of contact, cool, but I'm not really thrilled about adding another account to manage. I'm happy to roll it into my existing accounts.

**Comment by sf105** [comment]
I have an account with Gandi I use for all the Xmock domains. It looks like Gandi has support for multiple roles so I don’t mind adding hamcrest.org. Also, it doesn’t have automatic payments.

S

**Comment by offbyone** [comment]
Works for me! +1 on that.

**Comment by sf105** [comment]
Started the transfer. Further communication offline. Anyone else interested comment here.
